@extends('layouts.master-admin')

@section('title','Hasil Kuisioner per Mahasiswa')

@section('content')
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Hasil Kuisioner per Mahasiswa</h1>
<br><br>


<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
    <form>
            <div class="form-inline">
                <div class="form-group">
                    <label class=" mr-2" for="name">Tahun Akademik : </label>
                    <select name="" id="" class="form-control">
                        <option value="">2017 - 1</option>
                        <option value="">2017 - 2</option>
                    </select>
                </div>
                <button class=" ml-2 btn btn-primary">Tampilkan</button>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>NIM</th>
                        <th>Kelas</th>
                        <th>Tahun Akademik</th>
                        <th>Mata Kuliah</th>
                        <th>Dosen</th>
                        <th>IP</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>NIM</th>
                        <th>Kelas</th>
                        <th>Tahun Akademik</th>
                        <th>Mata Kuliah</th>
                        <th>Dosen</th>
                        <th>IP</th>
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td>16KAxon</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxrs</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxox</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxly</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxou</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxon</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxon</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxst</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxst</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxes</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxnn</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxll</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxdy</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxck</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxva</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxrd</td>
                        <td>16KA)</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxle</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxos</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxll</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxry</td>
                        <td>16KA)</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxce</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxos</td>
                        <td>16KA)</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxce</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxng</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxen</td>
                        <td>16KA)</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxou</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxse</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxks</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxtt</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxez</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxay</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxld</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxes</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxll</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxey</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxaw</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxng</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxsh</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxto</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxon</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxho</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxin</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxnk</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxno</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxta</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxns</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxce</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                    <tr>
                        <td>16KAxer</td>
                        <td>16KA</td>
                        <td>2017-2</td>
                        <td>Akutansi</td>
                        <td>Budiarto</td>
                        <td>3.4</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection


@push('script')
<script>
    //alert('ad')
</script>
<!-- Page level plugins -->
<script src="<?= url('/template-admin/vendor/datatables/jquery.dataTables.min.js') ?>"></script>
<script src="<?= url('/template-admin/vendor/datatables/dataTables.bootstrap4.min.js') ?>"></script>

<!-- Page level custom scripts -->
<script src="<?= url('/template-admin/js/demo/datatables-demo.js') ?>"></script>
@endpush
